name: Build

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Dockerhub login
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${DOCKER_HUB_TOKEN}" | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Build dockerfile (with push)
        run: |
          for filepath in systemd/*/*.Dockerfile;
          do
            dir=${filepath%/*}; file=${filepath##*/}; version=${file%.*}; flavor=${dir##*/};
            docker buildx build \
            --platform=linux/amd64,linux/arm/v8,linux/arm64 \
            --output "type=image,push=true" \
            --file ${filepath} . \
            --tag $(echo "${DOCKER_USERNAME}" | tr '[:upper:]' '[:lower:]')/systemd-${flavor}:${version}
          done
