name: Build

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build dockerfile (with push)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          for filepath in systemd/*/*.Dockerfile;
          do
            dir=${filepath%/*}; file=${filepath##*/}; version=${file%.*}; flavor=${dir##*/};
            echo "${filepath} ${version} ${flavor}";
            docker buildx build \
            --platform=linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --file "${filepath}" . \
            --tag "${DOCKER_HUB_USERNAME}/systemd-${flavor}:${version}"
          done
