name: Build

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build dockerfile (with push)
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap
          for filepath in systemd/*/*.Dockerfile;
          do
            dir=${filepath%/*}; file=${filepath##*/}; version=${file%.*}; flavor=${dir##*/};
            echo "${filepath} ${version} ${flavor}";
            docker buildx build \
            --platform=linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --file "${filepath}" . \
            --tag "${DOCKER_HUB_USERNAME}/systemd-${flavor}:${version}"
          done
