name: Ubuntu images build

on:
  push:
    branches: ['*']

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: systemd-ubuntu-16.04
            dockerfile: systemd/ubuntu/16.04.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              rnsc/systemd-ubuntu:16.04
              rnsc/systemd-ubuntu:xenial
          - name: systemd-ubuntu-18.04
            dockerfile: systemd/ubuntu/18.04.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              rnsc/systemd-ubuntu:18.04
              rnsc/systemd-ubuntu:bionic
          - name: systemd-ubuntu-20.04
            dockerfile: systemd/ubuntu/20.04.Dockerfile
            platforms: |-
              linux/amd64
              linux/arm/v7
              linux/arm64
            tags: |-
              rnsc/systemd-ubuntu:20.04
              rnsc/systemd-ubuntu:focal
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ matrix.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
